title:              Competitive Programming @ UW Bothell
shorttitle:         UWBCP
email:              uwbacm@uw.edu
description:        by UWB ACM chapter
author:             UWB ACM
baseurl:            "/"
markdown: kramdown
keywords: 
  - competitive programming 
  - uwb acm
  - uwb events
  - coding contest
  - uwb competitive programming
  - uwb acm programming contest
  - uwb competitive programming website
  - uwbcp
  - uwbcp website

# Social Profiles
discord_link:       https://discord.gg/2tWhanq
github_link:        https://github.com/UWB-ACM
linkedin_link:      https://www.linkedin.com/in/uwbacm/

# Google-analytics ID. Replace this field with GA id held by UWB ACM if needed.
google_analytics:   UA-xxxxxx 

# Build settings
paginate:           5
paginate_path:      "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
